export const GET_REMINDERS = 'GET_REMINDERS';
export const GET_REMINDERS_OK = 'GET_REMINDERS_OK';
export const GET_REMINDERS_ERROR = 'GET_REMINDERS_ERROR';

export const ADD_REMINDER = 'ADD_REMINDER';
export const ADD_REMINDER_OK = 'ADD_REMINDER_OK';
export const ADD_REMINDER_ERROR = 'ADD_REMINDER_ERROR';